"""Markdown renderer — for pasting into Confluence, Notion, PRs, etc."""

from ..models import AuditResult
from ..severity import severity_rank
from ._common import (
    VERDICT_EMOJI, CAT_LABELS, all_findings, scanned_by, display_scanner,
)


def to_markdown(result: AuditResult) -> str:
    v = result.overall_verdict
    emoji = VERDICT_EMOJI.get(v, "❓")
    lines = []

    lines += [
        f"# OSS Audit Report — `{result.repo_name}`",
        "",
        f"> **Repo:** {result.repo_url}  ",
        f"> **Profile:** `{result.profile}`  ",
        f"> **Scanned:** {result.timestamp}  ",
        f"> **Overall:** {emoji} **{v}** — {result.overall_reason}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        "| Category | Verdict | Critical | High | Medium | Low |",
        "|---|---|---|---|---|---|",
    ]

    for r in result.rubric:
        e = VERDICT_EMOJI.get(r.verdict, "?")
        lines.append(
            f"| {CAT_LABELS.get(r.category, r.category)} "
            f"| {e} {r.verdict} "
            f"| {r.critical_count} | {r.high_count} | {r.medium_count} | {r.low_count} |"
        )

    lines += ["", "---", "", "## Rubric Details", ""]
    for r in result.rubric:
        e = VERDICT_EMOJI.get(r.verdict, "?")
        cat_findings = [f for f in all_findings(result) if f.category == r.category]

        # Scanner attribution: who scanned this category (even if it found nothing).
        ran, not_installed = scanned_by(result, r.category)
        scanned_str = ", ".join(display_scanner(s) for s in ran) if ran else "—"
        n = len(cat_findings)
        scanned_line = f"**Scanned by:** {scanned_str} · {n} finding{'s' if n != 1 else ''}  "

        lines += [
            f"### {e} {CAT_LABELS.get(r.category, r.category)}",
            f"**Verdict:** {r.verdict}  ",
            f"**Reason:** {r.reason}  ",
            scanned_line,
        ]
        if not_installed:
            lines.append(f"**Not installed:** {', '.join(f'`{t}`' for t in not_installed)}  ")
        lines.append("")

        if cat_findings:
            # Show top 10 by severity
            cat_findings.sort(key=lambda f: severity_rank(f.severity))
            lines += ["| Severity | Title | Scanner | Location |",
                      "|---|---|---|---|"]
            for f in cat_findings[:10]:
                loc = f.location or "—"
                lines.append(f"| `{f.severity}` | {f.title} | `{f.scanner}` | `{loc}` |")
            if len(cat_findings) > 10:
                lines.append(f"_…and {len(cat_findings)-10} more. See JSON output for full list._")
            lines.append("")

    # Scanner coverage
    lines += ["---", "", "## Scanner Coverage", "",
              "| Scanner | Available | Ran | Findings | Duration |",
              "|---|---|---|---|---|"]
    for tr in result.scan_results:
        avail = "✅" if tr.available else "⬜ skipped"
        ran   = "✅" if tr.ran else "—"
        dur   = f"{tr.duration_s:.1f}s" if tr.ran else "—"
        lines.append(f"| {tr.scanner} | {avail} | {ran} | {len(tr.findings)} | {dur} |")

    if result.skipped_scanners:
        lines += ["",
                  f"> **Skipped scanners** (not installed): {', '.join(f'`{t}`' for t in result.skipped_scanners)}",
                  "> Install them to improve coverage."]

    lines += ["", "---", "",
              "_Generated by [oss-audit](https://github.com/your-org/oss-audit)_"]

    return "\n".join(lines)
